/*
 * This file is generated by jOOQ.
 */
package dao.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Address implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer addressId;
    private String addressLineOne;
    private String addressLineTwo;
    private String addressLineThree;
    private String addressLineFour;
    private String city;
    private String stateOrProvince;
    private String zipOrPostal;
    private String countryCode;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private LocalDateTime createdAt;
    private String placeId;

    public Address() {}

    public Address(Address value) {
        this.addressId = value.addressId;
        this.addressLineOne = value.addressLineOne;
        this.addressLineTwo = value.addressLineTwo;
        this.addressLineThree = value.addressLineThree;
        this.addressLineFour = value.addressLineFour;
        this.city = value.city;
        this.stateOrProvince = value.stateOrProvince;
        this.zipOrPostal = value.zipOrPostal;
        this.countryCode = value.countryCode;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.createdAt = value.createdAt;
        this.placeId = value.placeId;
    }

    public Address(
        Integer addressId,
        String addressLineOne,
        String addressLineTwo,
        String addressLineThree,
        String addressLineFour,
        String city,
        String stateOrProvince,
        String zipOrPostal,
        String countryCode,
        BigDecimal latitude,
        BigDecimal longitude,
        LocalDateTime createdAt,
        String placeId
    ) {
        this.addressId = addressId;
        this.addressLineOne = addressLineOne;
        this.addressLineTwo = addressLineTwo;
        this.addressLineThree = addressLineThree;
        this.addressLineFour = addressLineFour;
        this.city = city;
        this.stateOrProvince = stateOrProvince;
        this.zipOrPostal = zipOrPostal;
        this.countryCode = countryCode;
        this.latitude = latitude;
        this.longitude = longitude;
        this.createdAt = createdAt;
        this.placeId = placeId;
    }

    /**
     * Getter for <code>public.address.address_id</code>.
     */
    public Integer getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>public.address.address_id</code>.
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * Getter for <code>public.address.address_line_one</code>.
     */
    public String getAddressLineOne() {
        return this.addressLineOne;
    }

    /**
     * Setter for <code>public.address.address_line_one</code>.
     */
    public void setAddressLineOne(String addressLineOne) {
        this.addressLineOne = addressLineOne;
    }

    /**
     * Getter for <code>public.address.address_line_two</code>.
     */
    public String getAddressLineTwo() {
        return this.addressLineTwo;
    }

    /**
     * Setter for <code>public.address.address_line_two</code>.
     */
    public void setAddressLineTwo(String addressLineTwo) {
        this.addressLineTwo = addressLineTwo;
    }

    /**
     * Getter for <code>public.address.address_line_three</code>.
     */
    public String getAddressLineThree() {
        return this.addressLineThree;
    }

    /**
     * Setter for <code>public.address.address_line_three</code>.
     */
    public void setAddressLineThree(String addressLineThree) {
        this.addressLineThree = addressLineThree;
    }

    /**
     * Getter for <code>public.address.address_line_four</code>.
     */
    public String getAddressLineFour() {
        return this.addressLineFour;
    }

    /**
     * Setter for <code>public.address.address_line_four</code>.
     */
    public void setAddressLineFour(String addressLineFour) {
        this.addressLineFour = addressLineFour;
    }

    /**
     * Getter for <code>public.address.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>public.address.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>public.address.state_or_province</code>.
     */
    public String getStateOrProvince() {
        return this.stateOrProvince;
    }

    /**
     * Setter for <code>public.address.state_or_province</code>.
     */
    public void setStateOrProvince(String stateOrProvince) {
        this.stateOrProvince = stateOrProvince;
    }

    /**
     * Getter for <code>public.address.zip_or_postal</code>.
     */
    public String getZipOrPostal() {
        return this.zipOrPostal;
    }

    /**
     * Setter for <code>public.address.zip_or_postal</code>.
     */
    public void setZipOrPostal(String zipOrPostal) {
        this.zipOrPostal = zipOrPostal;
    }

    /**
     * Getter for <code>public.address.country_code</code>.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Setter for <code>public.address.country_code</code>.
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for <code>public.address.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for <code>public.address.latitude</code>.
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for <code>public.address.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for <code>public.address.longitude</code>.
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * Getter for <code>public.address.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.address.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.address.place_id</code>.
     */
    public String getPlaceId() {
        return this.placeId;
    }

    /**
     * Setter for <code>public.address.place_id</code>.
     */
    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Address other = (Address) obj;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        if (this.addressLineOne == null) {
            if (other.addressLineOne != null)
                return false;
        }
        else if (!this.addressLineOne.equals(other.addressLineOne))
            return false;
        if (this.addressLineTwo == null) {
            if (other.addressLineTwo != null)
                return false;
        }
        else if (!this.addressLineTwo.equals(other.addressLineTwo))
            return false;
        if (this.addressLineThree == null) {
            if (other.addressLineThree != null)
                return false;
        }
        else if (!this.addressLineThree.equals(other.addressLineThree))
            return false;
        if (this.addressLineFour == null) {
            if (other.addressLineFour != null)
                return false;
        }
        else if (!this.addressLineFour.equals(other.addressLineFour))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.stateOrProvince == null) {
            if (other.stateOrProvince != null)
                return false;
        }
        else if (!this.stateOrProvince.equals(other.stateOrProvince))
            return false;
        if (this.zipOrPostal == null) {
            if (other.zipOrPostal != null)
                return false;
        }
        else if (!this.zipOrPostal.equals(other.zipOrPostal))
            return false;
        if (this.countryCode == null) {
            if (other.countryCode != null)
                return false;
        }
        else if (!this.countryCode.equals(other.countryCode))
            return false;
        if (this.latitude == null) {
            if (other.latitude != null)
                return false;
        }
        else if (!this.latitude.equals(other.latitude))
            return false;
        if (this.longitude == null) {
            if (other.longitude != null)
                return false;
        }
        else if (!this.longitude.equals(other.longitude))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.placeId == null) {
            if (other.placeId != null)
                return false;
        }
        else if (!this.placeId.equals(other.placeId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        result = prime * result + ((this.addressLineOne == null) ? 0 : this.addressLineOne.hashCode());
        result = prime * result + ((this.addressLineTwo == null) ? 0 : this.addressLineTwo.hashCode());
        result = prime * result + ((this.addressLineThree == null) ? 0 : this.addressLineThree.hashCode());
        result = prime * result + ((this.addressLineFour == null) ? 0 : this.addressLineFour.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.stateOrProvince == null) ? 0 : this.stateOrProvince.hashCode());
        result = prime * result + ((this.zipOrPostal == null) ? 0 : this.zipOrPostal.hashCode());
        result = prime * result + ((this.countryCode == null) ? 0 : this.countryCode.hashCode());
        result = prime * result + ((this.latitude == null) ? 0 : this.latitude.hashCode());
        result = prime * result + ((this.longitude == null) ? 0 : this.longitude.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.placeId == null) ? 0 : this.placeId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(addressId);
        sb.append(", ").append(addressLineOne);
        sb.append(", ").append(addressLineTwo);
        sb.append(", ").append(addressLineThree);
        sb.append(", ").append(addressLineFour);
        sb.append(", ").append(city);
        sb.append(", ").append(stateOrProvince);
        sb.append(", ").append(zipOrPostal);
        sb.append(", ").append(countryCode);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(placeId);

        sb.append(")");
        return sb.toString();
    }
}
