version: '3.8'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    depends_on:
      - redis
      - db
    env_file: local.env
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    build: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -q -U docker"
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=public -user=docker -password=example -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
volumes:
  postgres-data: