name: test
on:
  issue_comment:
    if: github.event_name == 'pull_request' && contains(github.event.comment.body, '/support')
    types:
      - created
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hello"