name: test
on:
  issue_comment:
    types:
      - created
jobs:
  test:
    runs-on: ubuntu-latest
    if:  ${{startsWith(github.event.comment.body, '/support')}}
    steps:
      - name: test
        run: echo "hello"
  clean_up:
    runs-on: ubuntu-latest
    if: ${{!startsWith(github.event.comment.body, '/support')}}
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: cleanUp
        run: gh api -X DELETE /repos/JoshuaBb/Venue/actions/runs/${{github.run_id}}
