name: location Test Before Merge
env:
  working_dir: location
on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
jobs:
  test-location:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
        pip install -r test-requirements.txt
        pip install . e
      working-directory: env.working_dir

    - name: Run tests
      run: pytest  # Adjust as needed
      working-directory: env.working_dir

    - name: Comment on pull request
      if: success()
      run: |
        echo "Tests passed for $working_dir Service. Ready for merge!"
        # Add a comment to the pull request indicating that tests passed
        # Example: Add a comment with a success message
        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X POST \
          -d '{"body": "Tests passed. Ready for merge!"}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
